- gz_topic_name: "/x500/imu"
  ros_topic_name: "/x500/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"


- gz_topic_name: "/x500/air"
  ros_topic_name: "/x500/air"
  ros_type_name: "sensor_msgs/msg/FluidPressure"
  gz_type_name: "ignition.msgs.FluidPressure"
  direction: "GZ_TO_ROS"


- gz_topic_name: "/gps"
  ros_topic_name: "/x500/gps"
  gz_type_name: ignition.msgs.NavSat
  ros_type_name: sensor_msgs/msg/NavSatFix
  direction: GZ_TO_ROS

- gz_topic_name: "/x500/mag"
  ros_topic_name: "/x500/mag"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "ignition.msgs.Magnetometer"
  direction: "GZ_TO_ROS"


- gz_topic_name: "/model/x500_base/odometry"
  ros_topic_name: /x500/odometry
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: "GZ_TO_ROS"

- gz_topic_name: "/model/x500_base/pose"
  ros_topic_name: "/x500/pose"
  ros_type_name: "geometry_msgs/msg/PoseStamped"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: "GZ_TO_ROS"


- gz_topic_name: "/x500/command/motor_speed"
  ros_topic_name: "/x500/command/motor_speed"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "ignition.msgs.Actuators"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/world/drone_world/dynamic_pose"
  gz_topic_name: "/world/drone_world/dynamic_pose/info"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: "GZ_TO_ROS"